# Generated by Django 3.1.6 on 2021-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=25)),
                ('aiButton', models.BooleanField()),
                ('result', models.IntegerField(default=0)),
                ('aiType', models.CharField(max_length=100)),
                ('playerSkill', models.CharField(max_length=100)),
                ('aiCards', models.CharField(max_length=10)),
                ('playerCards', models.CharField(max_length=10)),
                ('commCards', models.CharField(max_length=50)),
            ],
        ),
    ]
